"""Add category field to goals

Revision ID: 17679866ef6b
Revises: 2e0c2bc98a3c
Create Date: 2025-08-23 08:02:26.279745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17679866ef6b'
down_revision = '2e0c2bc98a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
