"""Add completed_at field to Milestone model

Revision ID: 2e0c2bc98a3c
Revises: 1cf65d1bd2d4
Create Date: 2025-08-22 11:55:22.252857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0c2bc98a3c'
down_revision = '1cf65d1bd2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
